//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Worker_has_Department = new HashSet<Worker_has_Department>();
        }
        [Required]
        [Display(Name = "Номер отдела")]
        public int ID_Department { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 100 символов")]
        [Display(Name = "Наименование отдела")]
        public string Name { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Число должно быть положительным")]
        [Display(Name = "Кол-во закрепленных помещений")]
        public Nullable<int> Numb_Rooms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker_has_Department> Worker_has_Department { get; set; }
    }
}
