//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KadryEntities : DbContext
    {
        public KadryEntities()
            : base("name=KadryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Worker_has_Children> Worker_has_Children { get; set; }
        public virtual DbSet<Worker_has_Department> Worker_has_Department { get; set; }
    
        public virtual ObjectResult<Work_chi_Result> Work_chi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Work_chi_Result>("Work_chi");
        }
    
        public virtual ObjectResult<Work_wrk_Result> Work_wrk(string dname, System.DateTime vdate)
        {
            var dnameParameter = dname != null ?
                new ObjectParameter("dname", dname) :
                new ObjectParameter("dname", typeof(string));
    
            var vdateParameter = vdate != null ?
                new ObjectParameter("vdate", vdate) :
                new ObjectParameter("vdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Work_wrk_Result>("Work_wrk", dnameParameter, vdateParameter);
        }
    }
}
