//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Worker_has_Department = new HashSet<Worker_has_Department>();
            this.Worker_has_Children = new HashSet<Worker_has_Children>();
        }


        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Число должно быть положительным")]
        [Display(Name = "Таблеьный номер")]
        public int N_worker { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 100 символов")]
        [Display(Name = "ФИО")]
        public string Full_Name { get; set; }
        [Required]
        [StringLength(11, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 11 символов")]
        [Display(Name = "Паспорт")]
        public string Passport { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 100 символов")]
        [Display(Name = "Адрес")]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Birthday { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 20 символов")]
        [Display(Name = "Пол")]
        public string Sex { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Длина строки должна быть от 1 до 50 символов")]
        [Display(Name = "Должность")]
        public string Post { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Число должно быть положительным")]
        [Display(Name = "Кол-во детей")]
        public Nullable<int> Аmount_of_children { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker_has_Department> Worker_has_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker_has_Children> Worker_has_Children { get; set; }
    }
}
