//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Worker_has_Department
    {
        public int ID_Appointment { get; set; }
        [Required]
        [Display(Name = "Табельный номер - ФИО")]
        public int Worker_N_worker { get; set; }
        [Required]
        [Display(Name = "Номер отдела- наименование")]
        public int Department_ID_Department { get; set; }
        [Required]
        [Display(Name = "Дата начала работы")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_Start { get; set; }
        [Display(Name = "Дата окончания работы")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_End { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
